import { useStore } from "../../store/appStore";
import { setAnalyseResult, toggleInfluence } from "../../store/actions";
import type { AnalyseResult } from "../../types";

interface AnalysePanelProps {
  result: AnalyseResult;
  source: "claude" | "local";
}

export function AnalysePanel({ result, source }: AnalysePanelProps) {
  const { state, dispatch } = useStore();
  const nameOf = (id: string) => state.precedents.find((p) => p.id === id)?.name ?? id;
  const isInfluence = (id: string) => !!state.precedents.find((p) => p.id === id)?.isInfluence;

  const dismiss = (precedentId: string) =>
    dispatch(
      setAnalyseResult({
        ...result,
        recommendations: result.recommendations.filter((r) => r.precedentId !== precedentId),
      }),
    );

  return (
    <div className="rounded-lg border border-hairline bg-surface-1 p-4">
      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-[11px] font-medium uppercase tracking-wide text-ink-tertiary">
          Analyse results
        </h3>
        <span
          className="rounded-full bg-surface-3 px-2 py-0.5 text-[10px] text-ink-subtle"
          title={
            source === "claude"
              ? "Generated by the Claude API"
              : "Generated offline by tag-overlap logic (no API key set)"
          }
        >
          {source === "claude" ? "Claude" : "offline"}
        </span>
      </div>

      {result.recommendations.length === 0 ? (
        <p className="text-[12px] text-ink-tertiary">
          No precedents overlap with your concept tags yet.
        </p>
      ) : (
        <div className="flex flex-col gap-3">
          {result.recommendations.map((rec) => {
            const confirmed = isInfluence(rec.precedentId);
            return (
              <div key={rec.precedentId} className="border-b border-hairline pb-3 last:border-0 last:pb-0">
                <div className="text-[12px] font-medium text-ink">{nameOf(rec.precedentId)}</div>
                <p className="mt-0.5 text-[11px] leading-relaxed text-ink-muted">{rec.reason}</p>
                <div className="mt-2 flex gap-2">
                  <button
                    type="button"
                    onClick={() => dispatch(toggleInfluence(rec.precedentId, !confirmed))}
                    className={`rounded px-2 py-0.5 text-[10px] font-medium transition-colors ${
                      confirmed
                        ? "bg-primary text-on-primary"
                        : "border border-hairline-strong text-ink-subtle hover:border-primary hover:text-primary"
                    }`}
                  >
                    {confirmed ? "✓ influence" : "confirm"}
                  </button>
                  <button
                    type="button"
                    onClick={() => dismiss(rec.precedentId)}
                    className="rounded px-2 py-0.5 text-[10px] text-ink-tertiary transition-colors hover:text-ink"
                  >
                    dismiss
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {result.gaps.length > 0 && (
        <div className="mt-3 border-t border-hairline pt-3">
          <div className="mb-1.5 text-[10px] font-medium uppercase tracking-wide text-ink-tertiary">
            Gaps
          </div>
          <ul className="flex flex-col gap-1">
            {result.gaps.map((gap) => (
              <li key={gap} className="text-[11px] leading-relaxed text-ink-muted">
                · {gap}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
