import type { Precedent } from "../types";

// Real precedent library sourced from Divisare, with colours extracted directly
// from each project's image.
export const SEED_PRECEDENTS: Precedent[] = [
  {
    id: "obr-mind-west-gate",
    name: "Mind West Gate Innovation Hub",
    architect: "OBR Architects",
    year: 2022,
    demonstrates: "An open cube with full-height colonnades and a photovoltaic roof canopy is designed as a flexible, carbon-zero hub that listens to its users and adapts over time. (Milan, Italy)",
    tags: ["civic", "institutional", "glass", "steel", "canopy", "transparency"],
    swatches: [
      { hex: "#95ABB5", label: "", sourceId: "obr-mind-west-gate" },
      { hex: "#25291A", label: "", sourceId: "obr-mind-west-gate" },
      { hex: "#D3D6D0", label: "", sourceId: "obr-mind-west-gate" },
      { hex: "#43432D", label: "", sourceId: "obr-mind-west-gate" },
      { hex: "#698395", label: "", sourceId: "obr-mind-west-gate" },
      { hex: "#625F4B", label: "", sourceId: "obr-mind-west-gate" },
      { hex: "#8B8270", label: "", sourceId: "obr-mind-west-gate" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_800/v1657025605/t6k4lnkknz0e84kpct6r/obr-mind-west-gate-innovation-hub.jpg",
  },
  {
    id: "gautier-rey-fundamental",
    name: "Fundamental — Children's Playschool (Amsterdam International Competition)",
    architect: "Gautier Rey",
    year: 2016,
    demonstrates: "A linear kindergarten on a peninsula uses a double-skin facade to mediate between formal classrooms and informal play, keeping the site open, flexible and permeable. (Amsterdam, Netherlands)",
    tags: ["educational", "civic", "permeability", "in-between"],
    swatches: [
      { hex: "#E7D9CE", label: "", sourceId: "gautier-rey-fundamental" },
      { hex: "#ECF3FD", label: "", sourceId: "gautier-rey-fundamental" },
      { hex: "#E3EDFA", label: "", sourceId: "gautier-rey-fundamental" },
      { hex: "#C7AE87", label: "", sourceId: "gautier-rey-fundamental" },
      { hex: "#D9C8AC", label: "", sourceId: "gautier-rey-fundamental" },
      { hex: "#A8C1BF", label: "", sourceId: "gautier-rey-fundamental" },
      { hex: "#75847D", label: "", sourceId: "gautier-rey-fundamental" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1504811196/ztuzudcaj3ki1skhovcs/gautier-rey-fundamental.jpg",
  },
  {
    id: "raamwerk-youth-center",
    name: "Youth Center",
    architect: "RAAMWERK",
    year: 2016,
    demonstrates: "Exposed brick volumes are arranged around two exterior chambers to create a layered, theatre-like youth centre where residents can both observe and be observed. (Lichtervelde, Belgium)",
    tags: ["educational", "civic", "brick", "concrete", "drama", "enclosure"],
    swatches: [
      { hex: "#D68A9A", label: "", sourceId: "raamwerk-youth-center" },
      { hex: "#C06B7B", label: "", sourceId: "raamwerk-youth-center" },
      { hex: "#D5C5C9", label: "", sourceId: "raamwerk-youth-center" },
      { hex: "#BEA8AD", label: "", sourceId: "raamwerk-youth-center" },
      { hex: "#97363B", label: "", sourceId: "raamwerk-youth-center" },
      { hex: "#E0D4D6", label: "", sourceId: "raamwerk-youth-center" },
      { hex: "#F7F5F7", label: "", sourceId: "raamwerk-youth-center" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1499344810/yrr9qynolnsmuvnkalmi/raamwerk-youth-center.jpg",
  },
  {
    id: "cantine-d-assouinde",
    name: "Cantine d'Assouindé",
    architect: "Cécile-Diama Samb, Angelo Renna",
    year: 2017,
    demonstrates: "A single roof shelters a dining hall and kitchen built with local construction methods, doubling as a communal gathering space for the village. (Assouindé, Côte d'Ivoire)",
    tags: ["civic", "educational", "vernacular", "warmth"],
    swatches: [
      { hex: "#E2E1D4", label: "", sourceId: "cantine-d-assouinde" },
      { hex: "#E7D5C7", label: "", sourceId: "cantine-d-assouinde" },
      { hex: "#98BDB7", label: "", sourceId: "cantine-d-assouinde" },
      { hex: "#E5DDCF", label: "", sourceId: "cantine-d-assouinde" },
      { hex: "#E5D9CB", label: "", sourceId: "cantine-d-assouinde" },
      { hex: "#C4CABC", label: "", sourceId: "cantine-d-assouinde" },
      { hex: "#75A2AD", label: "", sourceId: "cantine-d-assouinde" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1491158019/vbbslze7hnsmsto77nai/cecile-diama-samb-angelo-renna-cantine-d-assouinde.jpg",
  },
  {
    id: "grassi-pavia",
    name: "Restructuring of a Monumental Building, Via Azario",
    architect: "Giorgio Grassi",
    year: 1966,
    demonstrates: "A heritage courtyard renovation uses ashlar stone and white masonry against red-painted stairwells to resize circulation while preserving the protected facades. (Pavia, Italy)",
    tags: ["adaptive-reuse", "institutional", "civic", "circulation", "palimpsest"],
    swatches: [
      { hex: "#E6E2D9", label: "", sourceId: "grassi-pavia" },
      { hex: "#14697C", label: "", sourceId: "grassi-pavia" },
      { hex: "#B87331", label: "", sourceId: "grassi-pavia" },
      { hex: "#E0DACE", label: "", sourceId: "grassi-pavia" },
      { hex: "#AB8060", label: "", sourceId: "grassi-pavia" },
      { hex: "#C7A582", label: "", sourceId: "grassi-pavia" },
      { hex: "#C8C1B3", label: "", sourceId: "grassi-pavia" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1487243123/magqkdvgrcku1xpkrm7n/giorgio-grassi-ristrutturazione-di-un-edificio-monumentale-in-via-azario-a-pavia.jpg",
  },
  {
    id: "gyrasium-sport",
    name: "The Gyrasium — Sport Facilities",
    architect: "Jean-Baptiste de Boisseson",
    year: 2016,
    demonstrates: "A multi-functional playground reuses the leftover land of an ordinary roundabout, turning under-used infrastructure into open, informal public sports space. (Paris, France)",
    tags: ["civic", "public-ground", "adaptive-reuse", "playfulness"],
    swatches: [
      { hex: "#EADAA2", label: "", sourceId: "gyrasium-sport" },
      { hex: "#98A2AB", label: "", sourceId: "gyrasium-sport" },
      { hex: "#B6D3DA", label: "", sourceId: "gyrasium-sport" },
      { hex: "#C2CDAD", label: "", sourceId: "gyrasium-sport" },
      { hex: "#E8EAE6", label: "", sourceId: "gyrasium-sport" },
      { hex: "#D4DFBA", label: "", sourceId: "gyrasium-sport" },
      { hex: "#CEDEDF", label: "", sourceId: "gyrasium-sport" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1481799240/oyopwzjepck0m97odgyu/jean-baptiste-de-boisseson-the-gyrasium-sport-facilities.jpg",
  },
  {
    id: "entre-deux-ponts",
    name: "Entre deux Ponts",
    architect: "Francesco Nicolai",
    year: 2016,
    demonstrates: "A long, thin new building connects two existing height levels and an out-of-scale neighbour, acting as a transparent architectural promenade between them. (Brussels, Belgium)",
    tags: ["in-between", "threshold", "transparency", "procession"],
    swatches: [
      { hex: "#B1A19E", label: "", sourceId: "entre-deux-ponts" },
      { hex: "#F3F2F2", label: "", sourceId: "entre-deux-ponts" },
      { hex: "#CDC7C5", label: "", sourceId: "entre-deux-ponts" },
      { hex: "#9E8984", label: "", sourceId: "entre-deux-ponts" },
      { hex: "#733132", label: "", sourceId: "entre-deux-ponts" },
      { hex: "#786B68", label: "", sourceId: "entre-deux-ponts" },
      { hex: "#444747", label: "", sourceId: "entre-deux-ponts" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1474644472/ga7xosgzs4fsn5jev4xa/francesco-nicolai-entre-deux-ponts.jpg",
  },
  {
    id: "renaissance-piazza",
    name: "Renaissance Piazza — Re-creation Centre, Lido Island (Venice International Competition)",
    architect: "Gautier Rey",
    year: 2016,
    demonstrates: "A new horizontal volume reunites four separated heritage buildings into one cultural centre, minimising intervention while restoring civic clarity to the waterfront. (Venice, Italy)",
    tags: ["civic", "public-ground", "adaptive-reuse", "dialogue"],
    swatches: [
      { hex: "#EDF1DB", label: "", sourceId: "renaissance-piazza" },
      { hex: "#F9FAF2", label: "", sourceId: "renaissance-piazza" },
      { hex: "#E1ECEB", label: "", sourceId: "renaissance-piazza" },
      { hex: "#E1EACA", label: "", sourceId: "renaissance-piazza" },
      { hex: "#D2E0B6", label: "", sourceId: "renaissance-piazza" },
      { hex: "#E4CACB", label: "", sourceId: "renaissance-piazza" },
      { hex: "#BFDDDE", label: "", sourceId: "renaissance-piazza" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1504812373/lyvcjzij7uhlaa9uszgi/gautier-rey-renaissance-piazza.jpg",
  },
  {
    id: "sorrento-house",
    name: "Sorrento House",
    architect: "Victoria Merrett",
    year: 2026,
    demonstrates: "Colorbond roofing, recycled brick and timber shiplap are assembled with restraint so the house aligns with, rather than imposes on, its suburban street. (Sorrento, Mornington Peninsula, Australia)",
    tags: ["domestic", "coast", "timber", "stone", "steel", "austerity", "vernacular"],
    swatches: [
      { hex: "#807665", label: "", sourceId: "sorrento-house" },
      { hex: "#EEE2CA", label: "", sourceId: "sorrento-house" },
      { hex: "#AA967B", label: "", sourceId: "sorrento-house" },
      { hex: "#F2E8D2", label: "", sourceId: "sorrento-house" },
      { hex: "#5D583B", label: "", sourceId: "sorrento-house" },
      { hex: "#39301D", label: "", sourceId: "sorrento-house" },
      { hex: "#C5B9A6", label: "", sourceId: "sorrento-house" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1780932964/49df9d3c-fd46-4972-a7f3-6aeb119c2deb/victoria-merrett-tasha-tylee-sorrento-house.jpg",
  },
  {
    id: "ironbark-house",
    name: "Ironbark House",
    architect: "Not All Architecture",
    year: 2025,
    demonstrates: "Inspired by Utzon's additive architecture, repeated bays of dense ironbark cladding and galvanised steel step across the site's contours to shelter a family from coastal extremes. (South-West Coast, Australia)",
    tags: ["domestic", "timber", "coast", "steel", "refuge", "sequence"],
    swatches: [
      { hex: "#F4F2F0", label: "", sourceId: "ironbark-house" },
      { hex: "#A18E74", label: "", sourceId: "ironbark-house" },
      { hex: "#F7EEEB", label: "", sourceId: "ironbark-house" },
      { hex: "#B7A487", label: "", sourceId: "ironbark-house" },
      { hex: "#7F6F5B", label: "", sourceId: "ironbark-house" },
      { hex: "#3E2F2C", label: "", sourceId: "ironbark-house" },
      { hex: "#C1BEB0", label: "", sourceId: "ironbark-house" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1778164318/ee45850a-9079-4320-9603-f7f458dc1fe1/not-all-architecture-dan-preston-ironbark-house.jpg",
  },
  {
    id: "stuartholme-house",
    name: "Stuartholme House",
    architect: "NIELSEN JENKINS, Michael Lumby",
    year: 2025,
    demonstrates: "A new lounge and bedroom suite is sunk slightly into the hillside to frame a private courtyard, balancing bushfire-rated glazing with a deliberate sense of refuge. (Brisbane, Australia)",
    tags: ["domestic", "brick", "refuge", "topography", "intimacy"],
    swatches: [
      { hex: "#1D230C", label: "", sourceId: "stuartholme-house" },
      { hex: "#6B6630", label: "", sourceId: "stuartholme-house" },
      { hex: "#454818", label: "", sourceId: "stuartholme-house" },
      { hex: "#8D8253", label: "", sourceId: "stuartholme-house" },
      { hex: "#AC9E7C", label: "", sourceId: "stuartholme-house" },
      { hex: "#DCC5AE", label: "", sourceId: "stuartholme-house" },
      { hex: "#8F8630", label: "", sourceId: "stuartholme-house" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1762438447/aafea96e-9e69-4400-83f4-7ef998d14170/nielsen-jenkins-michael-lumby-tom-ross-stuartholme-house.jpg",
  },
  {
    id: "egerton-street-house",
    name: "Egerton Street House",
    architect: "JULIAN LEGG",
    year: 2025,
    demonstrates: "Robust masonry volumes and delicate timber screens combine to give the coastal home privacy from the street while still drawing light deep into the interior. (Blairgowrie, Australia)",
    tags: ["domestic", "coast", "timber", "stone", "light", "intimacy"],
    swatches: [
      { hex: "#9D8E6F", label: "", sourceId: "egerton-street-house" },
      { hex: "#766C4D", label: "", sourceId: "egerton-street-house" },
      { hex: "#D5E7D5", label: "", sourceId: "egerton-street-house" },
      { hex: "#E4F4E3", label: "", sourceId: "egerton-street-house" },
      { hex: "#CADCCB", label: "", sourceId: "egerton-street-house" },
      { hex: "#464530", label: "", sourceId: "egerton-street-house" },
      { hex: "#B9BA9E", label: "", sourceId: "egerton-street-house" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1759325599/b8a88a70-6512-4faa-b5ec-e0338ff8e337/julian-legg-benji-bradley-egerton-street-house.jpg",
  },
  {
    id: "house-shaped-house",
    name: "House Shaped House",
    architect: "Atelier of Spatial Matters",
    year: 2025,
    demonstrates: "A mesh facade abstracts a Singapore bungalow into a white box, exposing domestic infrastructure as sculptural monoliths that organise the plan. (Singapore)",
    tags: ["domestic", "materiality"],
    swatches: [
      { hex: "#F1F1EE", label: "", sourceId: "house-shaped-house" },
      { hex: "#E1E0DC", label: "", sourceId: "house-shaped-house" },
      { hex: "#F6F6F4", label: "", sourceId: "house-shaped-house" },
      { hex: "#D5D1CE", label: "", sourceId: "house-shaped-house" },
      { hex: "#EAE9E5", label: "", sourceId: "house-shaped-house" },
      { hex: "#B4B2B5", label: "", sourceId: "house-shaped-house" },
      { hex: "#7B859C", label: "", sourceId: "house-shaped-house" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1741620351/a7d9bce2-5f6e-45dd-bd5b-cac1570110fb/atelier-of-spatial-matters-house-shaped-house.jpg",
  },
  {
    id: "barba-jupiter",
    name: "Barba Jupiter",
    architect: "GÉOMÉTRAL",
    year: 2024,
    demonstrates: "A strictly linear plan of stone walls, deep overhanging roofs and ventilating arches opens every room to the Atlantic horizon, drawing on Mediterranean archetypes. (Porquerolles Island, France)",
    tags: ["domestic", "coast", "horizon", "vernacular", "wind"],
    swatches: [
      { hex: "#FDE456", label: "", sourceId: "barba-jupiter" },
      { hex: "#FEEA62", label: "", sourceId: "barba-jupiter" },
      { hex: "#D0CCD0", label: "", sourceId: "barba-jupiter" },
      { hex: "#FCE049", label: "", sourceId: "barba-jupiter" },
      { hex: "#53484E", label: "", sourceId: "barba-jupiter" },
      { hex: "#979196", label: "", sourceId: "barba-jupiter" },
      { hex: "#F9E978", label: "", sourceId: "barba-jupiter" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1718361378/d2b40061-2984-4890-9ef0-bc6b3858ab6a/geometral-barba-jupiter.jpg",
  },
  {
    id: "house-three-gestures",
    name: "House with Three Gestures",
    architect: "Fala Atelier",
    year: 2021,
    demonstrates: "Denied a construction permit, the project is given away for free in full, in case someone else wants to build its unconditional charisma elsewhere. (Porto, Portugal)",
    tags: ["domestic", "sequence", "narrative"],
    swatches: [
      { hex: "#31575E", label: "", sourceId: "house-three-gestures" },
      { hex: "#365E69", label: "", sourceId: "house-three-gestures" },
      { hex: "#B7D0C1", label: "", sourceId: "house-three-gestures" },
      { hex: "#2E4B50", label: "", sourceId: "house-three-gestures" },
      { hex: "#EAEBEB", label: "", sourceId: "house-three-gestures" },
      { hex: "#0D191B", label: "", sourceId: "house-three-gestures" },
      { hex: "#819595", label: "", sourceId: "house-three-gestures" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1653896062/irrkykm0urpfim0zmrru/fala-atelier-house-with-three-gestures.jpg",
  },
  {
    id: "future-living-space",
    name: "050 WW — Future Living Space",
    architect: "Operadora",
    year: 2018,
    demonstrates: "Rather than design a house, the project proposes a digital platform letting inhabitants actively shape and adapt pre-existing housing structures themselves. (Shanghai, China)",
    tags: ["domestic", "adaptive-reuse"],
    swatches: [
      { hex: "#5E99CA", label: "", sourceId: "future-living-space" },
      { hex: "#C9855A", label: "", sourceId: "future-living-space" },
      { hex: "#8788AC", label: "", sourceId: "future-living-space" },
      { hex: "#3F78BE", label: "", sourceId: "future-living-space" },
      { hex: "#234BA3", label: "", sourceId: "future-living-space" },
      { hex: "#C8ACB8", label: "", sourceId: "future-living-space" },
      { hex: "#9F4C39", label: "", sourceId: "future-living-space" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1540488604/nqh6rsm1b8cbayjp1c4e/operadora-050-w-wu-future-living-space.png",
  },
  {
    id: "three-brothers-spania-dolina",
    name: "Three Brothers for Spania Dolina",
    architect: "Marek Nedelka",
    year: 2015,
    demonstrates: "Three small black-shingled buildings — a spa, a lodge and a bunkhouse — share one construction grid to reconnect an old mining village to active tourism. (Spania Dolina, Slovakia)",
    tags: ["domestic", "topography", "vernacular"],
    swatches: [
      { hex: "#FFFFFF", label: "", sourceId: "three-brothers-spania-dolina" },
      { hex: "#070707", label: "", sourceId: "three-brothers-spania-dolina" },
      { hex: "#FBFBFB", label: "", sourceId: "three-brothers-spania-dolina" },
      { hex: "#C4C4C4", label: "", sourceId: "three-brothers-spania-dolina" },
      { hex: "#EDEDED", label: "", sourceId: "three-brothers-spania-dolina" },
      { hex: "#727272", label: "", sourceId: "three-brothers-spania-dolina" },
      { hex: "#FFFFFF", label: "", sourceId: "three-brothers-spania-dolina" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1488463176/krpv6vtgxqtcuxnoiywx/marek-nedelka-three-brothers-for-spania-dolina.jpg",
  },
  {
    id: "morella-mosman",
    name: "\"Morella\", 5 Morella Rd, Mosman",
    architect: "SUPERCONTEXT",
    year: 2016,
    demonstrates: "A restoration and lightweight garden pavilion addition is conceived as deliberately voiceless, deferring entirely to the historic mansion's existing architectural language. (Sydney, Australia)",
    tags: ["domestic", "stone", "brick", "adaptive-reuse", "palimpsest"],
    swatches: [
      { hex: "#92918F", label: "", sourceId: "morella-mosman" },
      { hex: "#80746B", label: "", sourceId: "morella-mosman" },
      { hex: "#B3A99D", label: "", sourceId: "morella-mosman" },
      { hex: "#914B47", label: "", sourceId: "morella-mosman" },
      { hex: "#D2C7BA", label: "", sourceId: "morella-mosman" },
      { hex: "#5A3F38", label: "", sourceId: "morella-mosman" },
      { hex: "#F2F3F5", label: "", sourceId: "morella-mosman" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1487112356/x1xiodpffvytlnkioeqt/supercontext-morella-5-morella-rd-mosman.jpg",
  },
  {
    id: "lilyfield-house",
    name: "Lilyfield House",
    architect: "SUPERCONTEXT",
    year: 2016,
    demonstrates: "Lateral structural walls run the length of the house, opening side and rear walls to courtyards so timber screens and voids drive natural cross-ventilation. (Sydney, Australia)",
    tags: ["domestic", "timber", "brick", "void", "wind", "permeability"],
    swatches: [
      { hex: "#CFDADF", label: "", sourceId: "lilyfield-house" },
      { hex: "#AB9D83", label: "", sourceId: "lilyfield-house" },
      { hex: "#948B5F", label: "", sourceId: "lilyfield-house" },
      { hex: "#C6B59C", label: "", sourceId: "lilyfield-house" },
      { hex: "#626146", label: "", sourceId: "lilyfield-house" },
      { hex: "#808171", label: "", sourceId: "lilyfield-house" },
      { hex: "#22221F", label: "", sourceId: "lilyfield-house" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1487112590/e3d9fe9jywskovsmkrhp/supercontext-lilyfield-house.jpg",
  },
  {
    id: "uno8a-spoor",
    name: "SPOOR",
    architect: "UNO8A",
    year: 2016,
    demonstrates: "The building's own shape becomes the generative device that will trigger and host future extensions grafted onto it. (Bologna, Italy)",
    tags: ["concrete", "tectonic"],
    swatches: [
      { hex: "#406CB0", label: "", sourceId: "uno8a-spoor" },
      { hex: "#B3B2B4", label: "", sourceId: "uno8a-spoor" },
      { hex: "#8D8A8A", label: "", sourceId: "uno8a-spoor" },
      { hex: "#DFE0E2", label: "", sourceId: "uno8a-spoor" },
      { hex: "#6B6767", label: "", sourceId: "uno8a-spoor" },
      { hex: "#413C3A", label: "", sourceId: "uno8a-spoor" },
      { hex: "#0A3E7E", label: "", sourceId: "uno8a-spoor" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1495026800/cale7tqhocgogtbh8cc7/uno8a-spoor.jpg",
  },
  {
    id: "motoproprio-museo",
    name: "Museo",
    architect: "Motoproprio",
    year: 2015,
    demonstrates: "An enfilade of sculptural volumes forms a chronological exhibition path, treating the museum itself as a civic monument and screen for the city. (Stockholm, Sweden)",
    tags: ["cultural", "sequence", "monumentality", "narrative"],
    swatches: [
      { hex: "#D7E0D9", label: "", sourceId: "motoproprio-museo" },
      { hex: "#D9E3DB", label: "", sourceId: "motoproprio-museo" },
      { hex: "#DBE5DE", label: "", sourceId: "motoproprio-museo" },
      { hex: "#ECC8D0", label: "", sourceId: "motoproprio-museo" },
      { hex: "#A5D5E8", label: "", sourceId: "motoproprio-museo" },
      { hex: "#D5AD8C", label: "", sourceId: "motoproprio-museo" },
      { hex: "#1B8280", label: "", sourceId: "motoproprio-museo" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1469489662/kxelnsx0lch0d7d1gv2p/motoproprio-museo.jpg",
  },
  {
    id: "mym-make-your-mark-milan",
    name: "Make Your Mark in Milan",
    architect: "JAS — just another story",
    year: 2014,
    demonstrates: "The project takes its cue from the layered meanings of 'fair' — market, charity sale, exhibition, and commotion — as a framework for a temporary urban event. (Milano, Italy)",
    tags: ["public-ground", "palimpsest", "narrative"],
    swatches: [
      { hex: "#C9E8E7", label: "", sourceId: "mym-make-your-mark-milan" },
      { hex: "#9FA893", label: "", sourceId: "mym-make-your-mark-milan" },
      { hex: "#D5ECED", label: "", sourceId: "mym-make-your-mark-milan" },
      { hex: "#EDF7F8", label: "", sourceId: "mym-make-your-mark-milan" },
      { hex: "#D8D0C6", label: "", sourceId: "mym-make-your-mark-milan" },
      { hex: "#C0BCAB", label: "", sourceId: "mym-make-your-mark-milan" },
      { hex: "#7F7D6C", label: "", sourceId: "mym-make-your-mark-milan" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1447946150/alribx6rcr5ibh6gts5h/jas-just-another-story-mym-make-your-mark-in-milan.png",
  },
  {
    id: "museo-nacional-afganistan",
    name: "Museo Nacional de Afganistán",
    architect: "AV62 Arquitectos",
    year: 2012,
    demonstrates: "Vaulted, deformable spaces echo the Mosque of Córdoba to create a flexible national museum balancing physical shelter with cultural and intellectual exchange. (Kabul, Afghanistan)",
    tags: ["cultural", "institutional", "rammed-earth", "dialogue", "refuge", "identity"],
    swatches: [
      { hex: "#C8C9BD", label: "", sourceId: "museo-nacional-afganistan" },
      { hex: "#8C8E6E", label: "", sourceId: "museo-nacional-afganistan" },
      { hex: "#B7B6A3", label: "", sourceId: "museo-nacional-afganistan" },
      { hex: "#9FA287", label: "", sourceId: "museo-nacional-afganistan" },
      { hex: "#7B7B5B", label: "", sourceId: "museo-nacional-afganistan" },
      { hex: "#E8EBEE", label: "", sourceId: "museo-nacional-afganistan" },
      { hex: "#5E6149", label: "", sourceId: "museo-nacional-afganistan" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1/project_images/3435349/KABUL_AV_PROYECTOS/av62-arquitectos-museo-nacional-de-afganistan.jpg",
  },
  {
    id: "landesmuseum-zurich",
    name: "Landesmuseum",
    architect: "Paredes Pedrosa Arquitectos",
    year: 2002,
    demonstrates: "New and old volumes form a loose-fitting unit linked by open space, slipping museum offices beneath the courtyard and public functions into a riverside pavilion. (Zurich, Switzerland)",
    tags: ["cultural", "institutional", "stone", "dialogue"],
    swatches: [
      { hex: "#EDECEB", label: "", sourceId: "landesmuseum-zurich" },
      { hex: "#FDFDFD", label: "", sourceId: "landesmuseum-zurich" },
      { hex: "#FAC77F", label: "", sourceId: "landesmuseum-zurich" },
      { hex: "#828F89", label: "", sourceId: "landesmuseum-zurich" },
      { hex: "#202723", label: "", sourceId: "landesmuseum-zurich" },
      { hex: "#D79865", label: "", sourceId: "landesmuseum-zurich" },
      { hex: "#CDC6BD", label: "", sourceId: "landesmuseum-zurich" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1/project_images/537612/1863313937/paredes-pedrosa-arquitectos-landesmuseum.jpg",
  },
  {
    id: "liget-budapest-museums",
    name: "Liget Budapest Museums",
    architect: "IaN+",
    year: 2014,
    demonstrates: "Two museums share one perforated grid of walls, using cut-out patios and water surfaces to dissolve the boundary between landscape, city and exhibition space. (Budapest, Hungary)",
    tags: ["cultural", "institutional", "public-ground", "concrete", "steel", "boundary", "permeability"],
    swatches: [
      { hex: "#C8C7BE", label: "", sourceId: "liget-budapest-museums" },
      { hex: "#6F5B55", label: "", sourceId: "liget-budapest-museums" },
      { hex: "#A9AEAA", label: "", sourceId: "liget-budapest-museums" },
      { hex: "#C8B59E", label: "", sourceId: "liget-budapest-museums" },
      { hex: "#A8716D", label: "", sourceId: "liget-budapest-museums" },
      { hex: "#4A3A39", label: "", sourceId: "liget-budapest-museums" },
      { hex: "#848883", label: "", sourceId: "liget-budapest-museums" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1/project_images/4918961/vista-piscina-rossa/ian-liget-budapest-museums.jpg",
  },
  {
    id: "guggenheim-helsinki",
    name: "Guggenheim Helsinki Design Competition",
    architect: "Gosplan, Francesco Librizzi, Raffaella Parodi, Valter Scelsi",
    year: 2014,
    demonstrates: "Wood, brick and steel compose an essential material palette that reads the historic waterfront city as the basis for the museum's elemental forms. (Helsinki, Finland)",
    tags: ["cultural", "institutional", "brick", "materiality", "vernacular"],
    swatches: [
      { hex: "#ECE9DC", label: "", sourceId: "guggenheim-helsinki" },
      { hex: "#C7CCC4", label: "", sourceId: "guggenheim-helsinki" },
      { hex: "#D9DACF", label: "", sourceId: "guggenheim-helsinki" },
      { hex: "#585D5F", label: "", sourceId: "guggenheim-helsinki" },
      { hex: "#9B8673", label: "", sourceId: "guggenheim-helsinki" },
      { hex: "#B8B29E", label: "", sourceId: "guggenheim-helsinki" },
      { hex: "#FCFCFA", label: "", sourceId: "guggenheim-helsinki" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1/project_images/4871730/2_the_yellow_rabbit_and_the_snow/gosplan-francesco-librizzi-raffaella-parodi-valter-scelsi-guggenheim-helsinki-design-competition.jpg",
  },
  {
    id: "public-pool-brittany",
    name: "Renovation and Extension of a Public Swimming Pool in Brittany",
    architect: "RAUM",
    year: 2022,
    demonstrates: "A black timber skin wraps and insulates the rehabilitated pool cluster, floating a new covered volume above the water while respecting the existing heritage structures. (Saint-Méen-le-Grand, France)",
    tags: ["civic", "adaptive-reuse", "water", "timber", "ceramic", "lightness", "dialogue"],
    swatches: [
      { hex: "#B18C75", label: "", sourceId: "public-pool-brittany" },
      { hex: "#99755D", label: "", sourceId: "public-pool-brittany" },
      { hex: "#AEA599", label: "", sourceId: "public-pool-brittany" },
      { hex: "#C6C0B7", label: "", sourceId: "public-pool-brittany" },
      { hex: "#84938B", label: "", sourceId: "public-pool-brittany" },
      { hex: "#4F8382", label: "", sourceId: "public-pool-brittany" },
      { hex: "#5E5549", label: "", sourceId: "public-pool-brittany" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1683287058/7ad92386-5cbd-4813-844f-41aaa1b7d524/raum-charles-bouchaib-renovation-and-extension-of-a-public-swimming-pool-in-britanny.jpg",
  },
  {
    id: "servin-le-vert",
    name: "Servìn le Vert — The Environmentally-Sustainable-Man",
    architect: "Beniamino Servino",
    year: 2009,
    demonstrates: "The project operates as a graphic and philosophical manifesto exploring human scale against sustainable architecture and landscapes of abandonment. (Caserta, Italy)",
    tags: ["vegetation", "landscape", "scale", "ecology", "ruin"],
    swatches: [
      { hex: "#5B732C", label: "", sourceId: "servin-le-vert" },
      { hex: "#F5F6F7", label: "", sourceId: "servin-le-vert" },
      { hex: "#EFF0F4", label: "", sourceId: "servin-le-vert" },
      { hex: "#809345", label: "", sourceId: "servin-le-vert" },
      { hex: "#E8E9EB", label: "", sourceId: "servin-le-vert" },
      { hex: "#1F3316", label: "", sourceId: "servin-le-vert" },
      { hex: "#B6C7B0", label: "", sourceId: "servin-le-vert" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1/project_images/3856004/ON-Landscape_LANDSCHAFT-by-MICHAEL-REISCH1_021/beniamino-servino-serven-le-vert-the-environmentally-sustainable-man-the-eco-sustainable-man.jpg",
  },
  {
    id: "pink-mammals",
    name: "Pink Mammals",
    architect: "Angelo Renna, Fabulism",
    year: 2015,
    demonstrates: "An elevated path lets a wildlife reserve remain self-limiting, with rain-collecting 'pink mammal' forms growing to support water, fire and food needs for the park. (Kruger Park, South Africa)",
    tags: ["landscape", "rain", "ecology", "playfulness"],
    swatches: [
      { hex: "#CAB965", label: "", sourceId: "pink-mammals" },
      { hex: "#B0AF62", label: "", sourceId: "pink-mammals" },
      { hex: "#BEF2F0", label: "", sourceId: "pink-mammals" },
      { hex: "#DCD29E", label: "", sourceId: "pink-mammals" },
      { hex: "#D3C380", label: "", sourceId: "pink-mammals" },
      { hex: "#8FC3B4", label: "", sourceId: "pink-mammals" },
      { hex: "#8E9250", label: "", sourceId: "pink-mammals" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1/project_images/5225066/Senza-titolo-1___/angelo-renna-fabulism-pink-mammals.jpg",
  },
  {
    id: "altagether-alta",
    name: "Altagether",
    architect: "Fabulism",
    year: 2017,
    demonstrates: "Flexible, vernacular-inspired structures act as growable, dissolvable activators across the Arctic town, replacing solid production with adaptive social infrastructure. (Alta, Norway)",
    tags: ["coast", "vernacular"],
    swatches: [
      { hex: "#3D5962", label: "", sourceId: "altagether-alta" },
      { hex: "#FAFAFA", label: "", sourceId: "altagether-alta" },
      { hex: "#B1BFB7", label: "", sourceId: "altagether-alta" },
      { hex: "#EDEEEE", label: "", sourceId: "altagether-alta" },
      { hex: "#CAD2CD", label: "", sourceId: "altagether-alta" },
      { hex: "#DEE2E0", label: "", sourceId: "altagether-alta" },
      { hex: "#8AA097", label: "", sourceId: "altagether-alta" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1512223750/p529xou4fzxw7vld0utc/fabulism-altagether.jpg",
  },
  {
    id: "blueprint-genova-porto",
    name: "Blueprint Genova — Riqualificazione del Porto di Genova (Progetto Ammesso)",
    architect: "Rrs-studio",
    year: 2016,
    demonstrates: "A repeated modular cell generates a long waterfront frontage, keeping each building legible at human scale while the harbour promenade ties commerce to the working port. (Genova, Italy)",
    tags: ["civic", "public-ground", "coast", "concrete", "timber", "glass", "scale", "sequence", "commercial"],
    swatches: [
      { hex: "#C7C6CF", label: "", sourceId: "blueprint-genova-porto" },
      { hex: "#DEE0ED", label: "", sourceId: "blueprint-genova-porto" },
      { hex: "#403232", label: "", sourceId: "blueprint-genova-porto" },
      { hex: "#A3A1AB", label: "", sourceId: "blueprint-genova-porto" },
      { hex: "#787687", label: "", sourceId: "blueprint-genova-porto" },
      { hex: "#241E1F", label: "", sourceId: "blueprint-genova-porto" },
      { hex: "#5A5457", label: "", sourceId: "blueprint-genova-porto" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1488652948/lmqyxkmebly5tnb8vxi3/rrs-studio-blueprint-genova-riqualificazione-del-porto-di-genova-progetto-ammesso.jpg",
  },
  {
    id: "blueprint-genova-competition",
    name: "Blueprint Competition",
    architect: "Gosplan, pia, UNO8A, False Mirror Office",
    year: 2016,
    demonstrates: "A blank existing pavilion is given a new public-facing facade, opening a planned canal to view and threading residential volumes around it. (Genova, Italy)",
    tags: ["civic", "public-ground", "coast", "concrete", "steel", "transparency", "threshold"],
    swatches: [
      { hex: "#A1A19E", label: "", sourceId: "blueprint-genova-competition" },
      { hex: "#C5D0CA", label: "", sourceId: "blueprint-genova-competition" },
      { hex: "#778486", label: "", sourceId: "blueprint-genova-competition" },
      { hex: "#3D595B", label: "", sourceId: "blueprint-genova-competition" },
      { hex: "#B2575D", label: "", sourceId: "blueprint-genova-competition" },
      { hex: "#E6BCBD", label: "", sourceId: "blueprint-genova-competition" },
      { hex: "#D1BE93", label: "", sourceId: "blueprint-genova-competition" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1487174066/rdcyiiojrfu9pwb8tkho/gosplan-pia-uno8a-false-mirror-office-blueprint-competition.jpg",
  },
  {
    id: "15m-north-park",
    name: "15m North Park",
    architect: "De Gayardon Bureau",
    year: 2013,
    demonstrates: "One continuous waterfront park stitches the city and beach together along the coastline, treating Gabicce's public space as its primary touristic asset. (Gabicce Mare, Marche, Italy)",
    tags: ["public-ground", "coast", "landscape", "recreational"],
    swatches: [
      { hex: "#0A2F09", label: "", sourceId: "15m-north-park" },
      { hex: "#129811", label: "", sourceId: "15m-north-park" },
      { hex: "#07DED7", label: "", sourceId: "15m-north-park" },
      { hex: "#9DEEE4", label: "", sourceId: "15m-north-park" },
      { hex: "#5AE7E0", label: "", sourceId: "15m-north-park" },
      { hex: "#40A843", label: "", sourceId: "15m-north-park" },
      { hex: "#93C36B", label: "", sourceId: "15m-north-park" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1458814102/zmrrdlsrwixdo1jbmyrz/de-gayardon-bureau-15m-north-park.jpg",
  },
  {
    id: "phisyopolis-marsala",
    name: "Phisyopolis",
    architect: "CIRCOLO-A, LINEARAMA",
    year: 2016,
    demonstrates: "A Roman decumanus maximus is reinterpreted as the spine linking simple contemporary structures to archaeological remains across the park. (Marsala, Italy)",
    tags: ["public-ground", "landscape", "axis", "palimpsest", "dialogue"],
    swatches: [
      { hex: "#ECEFF4", label: "", sourceId: "phisyopolis-marsala" },
      { hex: "#C1BFAD", label: "", sourceId: "phisyopolis-marsala" },
      { hex: "#809A85", label: "", sourceId: "phisyopolis-marsala" },
      { hex: "#E6DFC6", label: "", sourceId: "phisyopolis-marsala" },
      { hex: "#5C574A", label: "", sourceId: "phisyopolis-marsala" },
      { hex: "#D0D2D4", label: "", sourceId: "phisyopolis-marsala" },
      { hex: "#CE9D73", label: "", sourceId: "phisyopolis-marsala" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_800/v1486637011/ozgben5tst6jgtq4dyoc/circolo-a-linearama-phisyopolis.jpg",
  },
  {
    id: "agora-library-copenhagen",
    name: "Agora 2.0 Library",
    architect: "Jean-Baptiste de Boisseson",
    year: 2014,
    demonstrates: "A traditional cylindrical book reserve is paired with an open 'library 2.0', translating the tension between print tradition and digital culture into two linked volumes. (Copenhagen, Denmark)",
    tags: ["educational", "cultural", "public-ground", "civic", "glass", "tension", "dialogue"],
    swatches: [
      { hex: "#EBEBEB", label: "", sourceId: "agora-library-copenhagen" },
      { hex: "#EEEEEE", label: "", sourceId: "agora-library-copenhagen" },
      { hex: "#B1B4B0", label: "", sourceId: "agora-library-copenhagen" },
      { hex: "#193232", label: "", sourceId: "agora-library-copenhagen" },
      { hex: "#F8F8F8", label: "", sourceId: "agora-library-copenhagen" },
      { hex: "#D2D5D1", label: "", sourceId: "agora-library-copenhagen" },
      { hex: "#928779", label: "", sourceId: "agora-library-copenhagen" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_800/v1466979152/imj2cjrzbsdasz5s3mcd/jean-baptiste-de-boisseson-agora-2-0-library.jpg",
  },
  {
    id: "childrens-home-funchal",
    name: "Children's Home Center",
    architect: "Pontoatelier",
    year: 2018,
    demonstrates: "A two-level central garden facing the sea anchors an intimate, homely atmosphere throughout the children's home's interior. (Funchal, Portugal)",
    tags: ["educational", "domestic", "coast", "concrete", "timber", "garden", "intimacy", "warmth"],
    swatches: [
      { hex: "#EAE3E0", label: "", sourceId: "childrens-home-funchal" },
      { hex: "#6D4A43", label: "", sourceId: "childrens-home-funchal" },
      { hex: "#8D7068", label: "", sourceId: "childrens-home-funchal" },
      { hex: "#D3CBC4", label: "", sourceId: "childrens-home-funchal" },
      { hex: "#B0958D", label: "", sourceId: "childrens-home-funchal" },
      { hex: "#1A148D", label: "", sourceId: "childrens-home-funchal" },
      { hex: "#3F3C32", label: "", sourceId: "childrens-home-funchal" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1541185395/mbrwuu5kwjj3xb9unpqv/pontoatelier-children-s-home-center.jpg",
  },
  {
    id: "lurago-derba-kindergarten",
    name: "Lurago d'Erba Kindergarten",
    architect: "Motoproprio",
    year: 2018,
    demonstrates: "Simple, colourful volumes are organised in stripes of play, service and teaching space, with movable furniture letting all five classrooms merge into one continuous room. (Lurago d'Erba, Italy)",
    tags: ["educational", "playfulness", "sequence"],
    swatches: [
      { hex: "#CEDDE4", label: "", sourceId: "lurago-derba-kindergarten" },
      { hex: "#A1B2AC", label: "", sourceId: "lurago-derba-kindergarten" },
      { hex: "#C6D6DD", label: "", sourceId: "lurago-derba-kindergarten" },
      { hex: "#ABBDC4", label: "", sourceId: "lurago-derba-kindergarten" },
      { hex: "#BACBD2", label: "", sourceId: "lurago-derba-kindergarten" },
      { hex: "#86877F", label: "", sourceId: "lurago-derba-kindergarten" },
      { hex: "#3E5A66", label: "", sourceId: "lurago-derba-kindergarten" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1533482634/l0ce3etc5uxil1t4ryj9/motoproprio-lurago-d-erba-kindergarten.jpg",
  },
  {
    id: "konntra-kindergarten",
    name: "Kindergarten",
    architect: "KONNTRA",
    year: 2018,
    demonstrates: "Citing Calvino's idea that every life is an encyclopedia of experience, the kindergarten is designed to give children space for critical thinking rather than strict upbringing. (Zagreb, Croatia)",
    tags: ["educational", "timber", "narrative", "identity"],
    swatches: [
      { hex: "#EAF7FD", label: "", sourceId: "konntra-kindergarten" },
      { hex: "#FCFCFC", label: "", sourceId: "konntra-kindergarten" },
      { hex: "#938966", label: "", sourceId: "konntra-kindergarten" },
      { hex: "#EAE9E7", label: "", sourceId: "konntra-kindergarten" },
      { hex: "#E4D6C4", label: "", sourceId: "konntra-kindergarten" },
      { hex: "#C6B492", label: "", sourceId: "konntra-kindergarten" },
      { hex: "#F2F2F2", label: "", sourceId: "konntra-kindergarten" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1532008217/fm9z0y5tprdt898wqiyw/konntra-kindergarten.jpg",
  },
  {
    id: "ecla-london",
    name: "ECLA",
    architect: "Giovanna Cavalli",
    year: 2015,
    demonstrates: "Echoing the same Calvino-inspired brief as Konntra, the design treats the early-years environment as formative architecture shaping a child's thinking and mood. (London, United Kingdom)",
    tags: ["educational", "timber", "glass", "narrative", "identity"],
    swatches: [
      { hex: "#BDA680", label: "", sourceId: "ecla-london" },
      { hex: "#9F825F", label: "", sourceId: "ecla-london" },
      { hex: "#DEC4A5", label: "", sourceId: "ecla-london" },
      { hex: "#826547", label: "", sourceId: "ecla-london" },
      { hex: "#A8B1AA", label: "", sourceId: "ecla-london" },
      { hex: "#ECE2D4", label: "", sourceId: "ecla-london" },
      { hex: "#90968C", label: "", sourceId: "ecla-london" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1480615681/efiocm63t3lrgxncbshf/giovanna-cavalli-ecla.jpg",
  },
  {
    id: "london-nursery-school",
    name: "London Nursery School",
    architect: "Mattia Grilli",
    year: 2015,
    demonstrates: "A small nursery school in Greenwich, London — no further design statement was published by the architect. (Greenwich, London, United Kingdom)",
    tags: ["educational", "timber"],
    swatches: [
      { hex: "#F9FAFB", label: "", sourceId: "london-nursery-school" },
      { hex: "#383230", label: "", sourceId: "london-nursery-school" },
      { hex: "#5D5547", label: "", sourceId: "london-nursery-school" },
      { hex: "#9BA4AB", label: "", sourceId: "london-nursery-school" },
      { hex: "#73716A", label: "", sourceId: "london-nursery-school" },
      { hex: "#211B1E", label: "", sourceId: "london-nursery-school" },
      { hex: "#D9DDDF", label: "", sourceId: "london-nursery-school" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1453368474/j7gujrmkjo9zguwqnenv/mattia-grilli-london-nursery-school.jpg",
  },
  {
    id: "bludoteca-milano",
    name: "Bludoteca",
    architect: "A2BC — Anna Angelelli, Antonio Bergamasco, Michela Cicuto",
    year: 2014,
    demonstrates: "Conceived as a 'folly', the pavilion plays uselessness against utility to reinterpret a decorative typology as a socially useful children's space. (Milano, Italy)",
    tags: ["educational", "playfulness"],
    swatches: [
      { hex: "#02A1F3", label: "", sourceId: "bludoteca-milano" },
      { hex: "#F2F4F7", label: "", sourceId: "bludoteca-milano" },
      { hex: "#058ADE", label: "", sourceId: "bludoteca-milano" },
      { hex: "#AECDE7", label: "", sourceId: "bludoteca-milano" },
      { hex: "#5FAEE1", label: "", sourceId: "bludoteca-milano" },
      { hex: "#0572C3", label: "", sourceId: "bludoteca-milano" },
      { hex: "#27A9EB", label: "", sourceId: "bludoteca-milano" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1/project_images/4759468/interior-01/a2bc-anna-angelelli-antonio-bergamasco-michela-cicuto-bludoteca.jpg",
  },
  {
    id: "ludoteca-padiglione-infanzia",
    name: "Ludoteca Padiglione Infanzia",
    architect: "STARTT",
    year: 2014,
    demonstrates: "A daycare wedged between tower blocks turns its site constraints into a sequence of synesthetic outdoor rooms, opening fully to the park through a totally openable fence. (Milano, Italy)",
    tags: ["educational", "civic", "ceramic", "timber", "sequence", "permeability", "playfulness"],
    swatches: [
      { hex: "#E0DFD6", label: "", sourceId: "ludoteca-padiglione-infanzia" },
      { hex: "#EDFAFD", label: "", sourceId: "ludoteca-padiglione-infanzia" },
      { hex: "#247381", label: "", sourceId: "ludoteca-padiglione-infanzia" },
      { hex: "#9FD1D6", label: "", sourceId: "ludoteca-padiglione-infanzia" },
      { hex: "#98846D", label: "", sourceId: "ludoteca-padiglione-infanzia" },
      { hex: "#455050", label: "", sourceId: "ludoteca-padiglione-infanzia" },
      { hex: "#4F99A2", label: "", sourceId: "ludoteca-padiglione-infanzia" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1/project_images/4757521/w_036_007/startt-ludoteca-padiglione-infanzia.jpg",
  },
  {
    id: "correze-sharing-islands",
    name: "La Corrèze — Sharing Islands (E13 Winner)",
    architect: "ARCHIPEL — Association d'Architectes",
    year: 2015,
    demonstrates: "Responding to rural car-dependency, the project reimagines housing around sharing and a citizen-centred approach rather than standardised, isolated living. (Ussel, Argentat, Turenne, France)",
    tags: ["public-ground", "water", "brick", "vernacular"],
    swatches: [
      { hex: "#7F8F71", label: "", sourceId: "correze-sharing-islands" },
      { hex: "#A4D2EF", label: "", sourceId: "correze-sharing-islands" },
      { hex: "#495D4A", label: "", sourceId: "correze-sharing-islands" },
      { hex: "#B9B196", label: "", sourceId: "correze-sharing-islands" },
      { hex: "#E6D8CE", label: "", sourceId: "correze-sharing-islands" },
      { hex: "#EDC6B0", label: "", sourceId: "correze-sharing-islands" },
      { hex: "#7CA6AE", label: "", sourceId: "correze-sharing-islands" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1452015064/lth0xnx1ceo2ofj1qd7h/archipel-association-d-architectes-la-correze-i-sharing-islands-i-e13-winner.jpg",
  },
  {
    id: "candy-shop-brussels",
    name: "The Candy Shop",
    architect: "Traumnovelle",
    year: 2016,
    demonstrates: "Domestic archetypes are gender-inverted and exaggerated to expose and critique the power relations embedded in conventional household space. (Brussels, Belgium)",
    tags: ["domestic", "narrative", "identity"],
    swatches: [
      { hex: "#0C0C0C", label: "", sourceId: "candy-shop-brussels" },
      { hex: "#212116", label: "", sourceId: "candy-shop-brussels" },
      { hex: "#34351C", label: "", sourceId: "candy-shop-brussels" },
      { hex: "#B5ACA4", label: "", sourceId: "candy-shop-brussels" },
      { hex: "#0A0A0A", label: "", sourceId: "candy-shop-brussels" },
      { hex: "#8E7D6C", label: "", sourceId: "candy-shop-brussels" },
      { hex: "#60574A", label: "", sourceId: "candy-shop-brussels" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1473624383/w9ysb1ruqkqwbxegkker/traumnovelle-the-candy-shop.jpg",
  },
  {
    id: "interior-exterior-mexico",
    name: "Interior/Exterior",
    architect: "Espacio Cero",
    year: 2014,
    demonstrates: "Three short provocations — an open-air chapel, a framed sky gallery, and an underground government building — each turn a civic void into public artwork. (Mexico City, Mexico)",
    tags: ["domestic", "boundary", "threshold", "void", "sacred", "institutional", "public-ground"],
    swatches: [
      { hex: "#8DA57C", label: "", sourceId: "interior-exterior-mexico" },
      { hex: "#428BA2", label: "", sourceId: "interior-exterior-mexico" },
      { hex: "#FCFDFC", label: "", sourceId: "interior-exterior-mexico" },
      { hex: "#719431", label: "", sourceId: "interior-exterior-mexico" },
      { hex: "#3D661A", label: "", sourceId: "interior-exterior-mexico" },
      { hex: "#C8D3BF", label: "", sourceId: "interior-exterior-mexico" },
      { hex: "#276F81", label: "", sourceId: "interior-exterior-mexico" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1446431589/mihkj4rum7u4nz8zsbkt/espacio-cero-interior-exterior.jpg",
  },
  {
    id: "qianhai-monument-shenzen",
    name: "Qianhai Monument Landscape Island",
    architect: "Viar Estudio",
    year: 2014,
    demonstrates: "Two parks are layered five metres apart, with elevated circular walkways letting visitors choose between sea views, sport, and a sheltered ground-level garden. (Shenzen, China)",
    tags: ["memorial", "public-ground", "landscape", "coast", "palimpsest", "refuge", "recreational"],
    swatches: [
      { hex: "#7D2424", label: "", sourceId: "qianhai-monument-shenzen" },
      { hex: "#6C8D60", label: "", sourceId: "qianhai-monument-shenzen" },
      { hex: "#E2E8DC", label: "", sourceId: "qianhai-monument-shenzen" },
      { hex: "#9AB685", label: "", sourceId: "qianhai-monument-shenzen" },
      { hex: "#88A173", label: "", sourceId: "qianhai-monument-shenzen" },
      { hex: "#716749", label: "", sourceId: "qianhai-monument-shenzen" },
      { hex: "#AFC69A", label: "", sourceId: "qianhai-monument-shenzen" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1445420561/cqqzjjbpchmmuunp6jpe/viar-estudio-qianhai-monument-landscape-island-shenzen-china.jpg",
  },
  {
    id: "lady-raval-housing",
    name: "Lady Raval Social Housing",
    architect: "MIAS Architects",
    year: 2025,
    demonstrates: "A rehabilitated tenement reopens its central courtyard as a communal canvas, using ceramic cladding patterned on residents' cultural heritage to express the building's multicultural community. (Barcelona, Spain)",
    tags: ["domestic", "civic", "ceramic", "brick", "adaptive-reuse", "identity", "narrative"],
    swatches: [
      { hex: "#CB6A63", label: "", sourceId: "lady-raval-housing" },
      { hex: "#BF4A42", label: "", sourceId: "lady-raval-housing" },
      { hex: "#C2B6B4", label: "", sourceId: "lady-raval-housing" },
      { hex: "#923B35", label: "", sourceId: "lady-raval-housing" },
      { hex: "#B0968A", label: "", sourceId: "lady-raval-housing" },
      { hex: "#846665", label: "", sourceId: "lady-raval-housing" },
      { hex: "#422826", label: "", sourceId: "lady-raval-housing" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1749737278/7a25b331-40ae-420e-8a26-0e8eeff1efa9/mias-architects-adria-goula-lady-raval-social-housing.jpg",
  },
  {
    id: "aidna-stempark",
    name: "Stempark at Masseria Ferraioli",
    architect: "AIDNA",
    year: 2025,
    demonstrates: "Dry-laid tufa bricks and basic recovered materials, built by former prisoners in social reintegration, lay out a square garden classroom of six rooms around a communal corridor on a former mafia-confiscated farm. (Afragola, Italy)",
    tags: ["garden", "vegetation", "civic", "educational", "earth", "adaptive-reuse", "narrative"],
    swatches: [
      { hex: "#9E8F3C", label: "", sourceId: "aidna-stempark" },
      { hex: "#7C5C36", label: "", sourceId: "aidna-stempark" },
      { hex: "#A47A50", label: "", sourceId: "aidna-stempark" },
      { hex: "#8F832F", label: "", sourceId: "aidna-stempark" },
      { hex: "#585315", label: "", sourceId: "aidna-stempark" },
      { hex: "#2B2907", label: "", sourceId: "aidna-stempark" },
      { hex: "#A69382", label: "", sourceId: "aidna-stempark" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_800/v1776965544/0d8e9c88-1f76-49f0-bd7b-9bc4d5dd3a3c/aidna-andrea-martino-stempark-at-masseria-ferraioli.jpg",
  },
  {
    id: "ofl-orto-di-nome-eva",
    name: "Un Orto di Nome Eva",
    architect: "OFL Architecture",
    year: 2023,
    demonstrates: "Seven reconfigurable steel planter modules turn a school courtyard into an always-changing outdoor laboratory mapped to the sequential stages of growing food. (Sora, Italy)",
    tags: ["garden", "educational", "steel", "sequence", "seasonality"],
    swatches: [
      { hex: "#E1D4C3", label: "", sourceId: "ofl-orto-di-nome-eva" },
      { hex: "#AD9E7D", label: "", sourceId: "ofl-orto-di-nome-eva" },
      { hex: "#D0BFA4", label: "", sourceId: "ofl-orto-di-nome-eva" },
      { hex: "#A4724A", label: "", sourceId: "ofl-orto-di-nome-eva" },
      { hex: "#F6F0E9", label: "", sourceId: "ofl-orto-di-nome-eva" },
      { hex: "#743A1B", label: "", sourceId: "ofl-orto-di-nome-eva" },
      { hex: "#EEA77A", label: "", sourceId: "ofl-orto-di-nome-eva" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_800/v1693929077/3614a366-0ae7-44e7-b475-9c27bdbba0f8/ofl-architecture-francesco-lipari-nine-associati-paolo-emilio-bellisario-emilia-caffo-matteo-di-sora-michele-boccia-un-orto-di-nome-eva.jpg",
  },
  {
    id: "woha-oasia-hotel",
    name: "Oasia Hotel Downtown",
    architect: "WOHA Design",
    year: 2016,
    demonstrates: "A perforated red aluminium screen lets the tower grow its own climbing vegetation, stacking sky gardens as open-sided verandahs that bring cross-ventilation and greenery deep into a dense high-rise. (Singapore)",
    tags: ["garden", "vegetation", "steel", "aluminium", "wind", "density", "hospitality"],
    swatches: [
      { hex: "#6EB0E6", label: "", sourceId: "woha-oasia-hotel" },
      { hex: "#E45628", label: "", sourceId: "woha-oasia-hotel" },
      { hex: "#BB321F", label: "", sourceId: "woha-oasia-hotel" },
      { hex: "#59240C", label: "", sourceId: "woha-oasia-hotel" },
      { hex: "#D98949", label: "", sourceId: "woha-oasia-hotel" },
      { hex: "#9A6D20", label: "", sourceId: "woha-oasia-hotel" },
      { hex: "#F1A57F", label: "", sourceId: "woha-oasia-hotel" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_800/v1489570502/hqhynvzmavulpwt7czqe/woha-design-k-kopter-patrick-bingham-hall-oasia-hotel-downtown.jpg",
  },
  {
    id: "unagru-house-for-cellist",
    name: "House for Cellist",
    architect: "Unagru Architecture Urbanism",
    year: 2021,
    demonstrates: "A brick-and-glass rear extension to a Victorian terrace opens a broken-plan living space directly onto the garden, giving a musician both a bright home and a place to play. (London, United Kingdom)",
    tags: ["domestic", "garden", "brick", "glass", "light"],
    swatches: [
      { hex: "#9CA286", label: "", sourceId: "unagru-house-for-cellist" },
      { hex: "#B6B29D", label: "", sourceId: "unagru-house-for-cellist" },
      { hex: "#848F68", label: "", sourceId: "unagru-house-for-cellist" },
      { hex: "#5F6C47", label: "", sourceId: "unagru-house-for-cellist" },
      { hex: "#CDC4B6", label: "", sourceId: "unagru-house-for-cellist" },
      { hex: "#343E24", label: "", sourceId: "unagru-house-for-cellist" },
      { hex: "#E0DBD6", label: "", sourceId: "unagru-house-for-cellist" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_800/v1679576703/96b69c21-a161-4308-bac7-bf1ae27532a8/unagru-architecture-urbanism-nick-dearden-house-for-cellist.jpg",
  },
  {
    id: "woolf-monks-house-garden",
    name: "Virginia Woolf's Garden at Monk's House",
    architect: "Leonard Woolf",
    year: 1919,
    demonstrates: "A densely planted cottage garden at the Woolfs' country retreat provided Virginia Woolf the solitude and grounding to write Mrs Dalloway and To the Lighthouse. (Rodmell, England)",
    tags: ["garden", "vegetation", "refuge", "intimacy", "stillness", "narrative"],
    swatches: [
      { hex: "#8C9363", label: "", sourceId: "woolf-monks-house-garden" },
      { hex: "#2B3C0E", label: "", sourceId: "woolf-monks-house-garden" },
      { hex: "#E8F3F9", label: "", sourceId: "woolf-monks-house-garden" },
      { hex: "#68831A", label: "", sourceId: "woolf-monks-house-garden" },
      { hex: "#ABB5B5", label: "", sourceId: "woolf-monks-house-garden" },
      { hex: "#556134", label: "", sourceId: "woolf-monks-house-garden" },
      { hex: "#68ACFA", label: "", sourceId: "woolf-monks-house-garden" },
    ],
    isInfluence: false,
    imageUrl: "https://images-production.gardenvisit.com/uploads/images/114640/monks_house_woolf2_original.jpg",
  },
  {
    id: "mvrdv-seoul-skygarden",
    name: "Seoul Skygarden",
    architect: "MVRDV",
    year: 2009,
    demonstrates: "254 species of local plants repopulate a condemned 1970s vehicular overpass, turning a demolished highway into a living plant library and pedestrian park through the city centre. (Seoul, South Korea)",
    tags: ["garden", "vegetation", "public-ground", "adaptive-reuse", "ecology"],
    swatches: [
      { hex: "#E2DDE4", label: "", sourceId: "mvrdv-seoul-skygarden" },
      { hex: "#857254", label: "", sourceId: "mvrdv-seoul-skygarden" },
      { hex: "#CFC7CA", label: "", sourceId: "mvrdv-seoul-skygarden" },
      { hex: "#BEB0AB", label: "", sourceId: "mvrdv-seoul-skygarden" },
      { hex: "#A9987D", label: "", sourceId: "mvrdv-seoul-skygarden" },
      { hex: "#4C412A", label: "", sourceId: "mvrdv-seoul-skygarden" },
      { hex: "#F8F5F7", label: "", sourceId: "mvrdv-seoul-skygarden" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_800/v1453463638/qes0y6akewqsftz3vzoe/mvrdv-seoul-skygarden.jpg",
  },
  {
    id: "chybik-kristof-forestry-campus",
    name: "Czech Forestry Commission Campus",
    architect: "CHYBIK + KRISTOF",
    year: 2017,
    demonstrates: "A five-fingered timber office building interleaves with a surrounding forest nature trail, designed to dissolve the boundary between inside office and outside ecotype. (Brno (Hradec Králové), Czechia)",
    tags: ["timber", "landscape", "vegetation", "topography", "institutional", "boundary", "workspace", "permeability"],
    swatches: [
      { hex: "#9CB7AF", label: "", sourceId: "chybik-kristof-forestry-campus" },
      { hex: "#ACADAF", label: "", sourceId: "chybik-kristof-forestry-campus" },
      { hex: "#BCABB5", label: "", sourceId: "chybik-kristof-forestry-campus" },
      { hex: "#8C9C93", label: "", sourceId: "chybik-kristof-forestry-campus" },
      { hex: "#CABA7E", label: "", sourceId: "chybik-kristof-forestry-campus" },
      { hex: "#C7B150", label: "", sourceId: "chybik-kristof-forestry-campus" },
      { hex: "#6E8073", label: "", sourceId: "chybik-kristof-forestry-campus" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_800/v1488551719/xpcndqzv0ngmfsykdekb/chybik-kristof-breathe-earth-collective-czech-forestry-commission-campus.jpg",
  },
  {
    id: "metropolitan-workshop-lewisham",
    name: "New Affordable Homes in Lewisham",
    architect: "Metropolitan Workshop",
    year: 2026,
    demonstrates: "Brick gatehouse dwellings built to the Passivhaus standard frame a new entry to affordable housing, drawing on the historic Bellingham estate's Garden City and Arts & Crafts character. (London, United Kingdom)",
    tags: ["domestic", "brick", "threshold", "vernacular"],
    swatches: [
      { hex: "#FAFAFB", label: "", sourceId: "metropolitan-workshop-lewisham" },
      { hex: "#D8CBC3", label: "", sourceId: "metropolitan-workshop-lewisham" },
      { hex: "#C78C6E", label: "", sourceId: "metropolitan-workshop-lewisham" },
      { hex: "#A3694F", label: "", sourceId: "metropolitan-workshop-lewisham" },
      { hex: "#D7AD97", label: "", sourceId: "metropolitan-workshop-lewisham" },
      { hex: "#4C3424", label: "", sourceId: "metropolitan-workshop-lewisham" },
      { hex: "#F1EFEE", label: "", sourceId: "metropolitan-workshop-lewisham" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_800/v1776344203/7f277166-95e1-445e-afff-fd74829cfe32/metropolitan-workshop-fred-haworth-new-affordable-homes-in-lewisham.jpg",
  },
  {
    id: "lopez-rivera-intergenerational-housing",
    name: "Intergenerational Social Housing",
    architect: "Emiliano López Mónica Rivera Arquitectos",
    year: 2024,
    demonstrates: "Two volumes frame a tree-lined patio for eighteen homes whose thick north and south walls passively store and release heat, achieving zero heating/cooling demand through entirely manual bioclimatic operation. (Esporles, Spain)",
    tags: ["domestic", "hybrid", "stone", "concrete", "steel", "garden", "warmth", "ecology", "heaviness"],
    swatches: [
      { hex: "#B9B79F", label: "", sourceId: "lopez-rivera-intergenerational-housing" },
      { hex: "#887046", label: "", sourceId: "lopez-rivera-intergenerational-housing" },
      { hex: "#A09A7E", label: "", sourceId: "lopez-rivera-intergenerational-housing" },
      { hex: "#5C4A20", label: "", sourceId: "lopez-rivera-intergenerational-housing" },
      { hex: "#E8E4D3", label: "", sourceId: "lopez-rivera-intergenerational-housing" },
      { hex: "#DDD4BD", label: "", sourceId: "lopez-rivera-intergenerational-housing" },
      { hex: "#CAD1C1", label: "", sourceId: "lopez-rivera-intergenerational-housing" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1744640074/2b646b66-9a46-4142-ad11-bef2d8bebdea/emiliano-lopez-monica-rivera-arquitectos-jose-hevia-intergenerational-social-housing.jpg",
  },
  {
    id: "not-a-studio-monterols",
    name: "Monterols",
    architect: "NOT A STUDIO (Rocco Bibbiani)",
    year: 2026,
    demonstrates: "A fragmented 36sqm family apartment is opened into one tall volume, with exposed structural beams and pillars painted blue, green and yellow to turn construction into art. (Barcelona, Spain)",
    tags: ["domestic", "timber", "steel", "ceramic", "adaptive-reuse", "fragment", "tectonic", "playfulness"],
    swatches: [
      { hex: "#988B83", label: "", sourceId: "not-a-studio-monterols" },
      { hex: "#C3C0BF", label: "", sourceId: "not-a-studio-monterols" },
      { hex: "#AFA7A2", label: "", sourceId: "not-a-studio-monterols" },
      { hex: "#6F6C68", label: "", sourceId: "not-a-studio-monterols" },
      { hex: "#967054", label: "", sourceId: "not-a-studio-monterols" },
      { hex: "#3B3B41", label: "", sourceId: "not-a-studio-monterols" },
      { hex: "#DEE0E6", label: "", sourceId: "not-a-studio-monterols" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1781619311/1fa0a536-ff00-4aef-b97c-5cf1f3e8101c/not-a-studio-rocco-bibbiani-monterols.jpg",
  },
  {
    id: "ten-house-for-five-women",
    name: "House for Five Women",
    architect: "TEN",
    year: 2025,
    demonstrates: "A rural house for women who survived war and violence is designed through an open, collaborative process to support self-determined, mutually responsible communal living. (Gradacac, Bosnia and Herzegovina)",
    tags: ["domestic", "refuge", "civic", "concrete", "glass", "identity", "narrative", "vernacular"],
    swatches: [
      { hex: "#8F937A", label: "", sourceId: "ten-house-for-five-women" },
      { hex: "#D7E8F5", label: "", sourceId: "ten-house-for-five-women" },
      { hex: "#CAB7B8", label: "", sourceId: "ten-house-for-five-women" },
      { hex: "#516448", label: "", sourceId: "ten-house-for-five-women" },
      { hex: "#E0F2FB", label: "", sourceId: "ten-house-for-five-women" },
      { hex: "#ECF8FC", label: "", sourceId: "ten-house-for-five-women" },
      { hex: "#F6FCFC", label: "", sourceId: "ten-house-for-five-women" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1742474494/f6b62b35-3e76-4817-b461-cd2a4e2c46f6/ten-maxime-delvaux-adrien-de-hemptinne-house-for-five-women.jpg",
  },
  {
    id: "studio-okami-riverside-tower",
    name: "Brutalist Duplex Apartment in the Riverside Tower",
    architect: "Studio Okami Architects",
    year: 2021,
    demonstrates: "Stripping a 1970s duplex back to its sandblasted structural concrete reveals a single open-plan loft spanning two floors of a brutalist riverside tower. (Antwerp, Belgium)",
    tags: ["domestic", "concrete", "steel", "adaptive-reuse", "rawness", "tectonic"],
    swatches: [
      { hex: "#B9BAB9", label: "", sourceId: "studio-okami-riverside-tower" },
      { hex: "#D5D6D6", label: "", sourceId: "studio-okami-riverside-tower" },
      { hex: "#8B9DAA", label: "", sourceId: "studio-okami-riverside-tower" },
      { hex: "#5D5F53", label: "", sourceId: "studio-okami-riverside-tower" },
      { hex: "#3177A3", label: "", sourceId: "studio-okami-riverside-tower" },
      { hex: "#80817B", label: "", sourceId: "studio-okami-riverside-tower" },
      { hex: "#313423", label: "", sourceId: "studio-okami-riverside-tower" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1655890400/vi8wzkynnyfglkxqrvcg/studio-okami-architects-olmo-peeters-matthijs-van-der-burgt-brutalist-duplex-apartement-in-the-riverside-tower.jpg",
  },
  {
    id: "studio-made-retreat-house",
    name: "The Retreat House",
    architect: "Studio MADE",
    year: 2020,
    demonstrates: "A retired couple's house is designed as an anonymous series of roofed and open-to-sky rooms within a walled compound, deliberately free of any conventional image of home. (Andhra Pradesh, India)",
    tags: ["domestic", "refuge", "brick", "timber", "void", "boundary", "sequence"],
    swatches: [
      { hex: "#A35C44", label: "", sourceId: "studio-made-retreat-house" },
      { hex: "#CA9075", label: "", sourceId: "studio-made-retreat-house" },
      { hex: "#3F2218", label: "", sourceId: "studio-made-retreat-house" },
      { hex: "#25120E", label: "", sourceId: "studio-made-retreat-house" },
      { hex: "#673D2C", label: "", sourceId: "studio-made-retreat-house" },
      { hex: "#E8E5E1", label: "", sourceId: "studio-made-retreat-house" },
      { hex: "#110706", label: "", sourceId: "studio-made-retreat-house" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1669902302/zorkkqfeqd4gpoqz5mdz/studio-made-ujjwal-sannala-the-retreat-house.jpg",
  },
  {
    id: "scalar-forest-retreat",
    name: "Forest Retreat CT",
    architect: "Scalar Architecture",
    year: 2022,
    demonstrates: "A compact, minimal-footprint timber box for a family of writers steps across a rocky forest clearing, with a roof opening that collects rain, light and ventilation around a central boulder courtyard. (East Coast Forest, USA)",
    tags: ["domestic", "refuge", "timber", "topography", "vegetation", "rain", "light", "wind", "austerity"],
    swatches: [
      { hex: "#74553B", label: "", sourceId: "scalar-forest-retreat" },
      { hex: "#9F8E6E", label: "", sourceId: "scalar-forest-retreat" },
      { hex: "#453C30", label: "", sourceId: "scalar-forest-retreat" },
      { hex: "#C6B6A7", label: "", sourceId: "scalar-forest-retreat" },
      { hex: "#231E19", label: "", sourceId: "scalar-forest-retreat" },
      { hex: "#52574F", label: "", sourceId: "scalar-forest-retreat" },
      { hex: "#7F8B8A", label: "", sourceId: "scalar-forest-retreat" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1669110194/r0nbowayjaqwt9ai6utf/scalar-architecture-imagensubliminal-miguel-de-guzman-rocio-romero-forest-retreat-ct.jpg",
  },
  {
    id: "chipperfield-inagawa-cemetery",
    name: "Inagawa Cemetery Chapel and Visitor Centre",
    architect: "David Chipperfield Architects",
    year: 2017,
    demonstrates: "A chapel and visitor centre gather around a courtyard garden under a single sloping roof, using earth-like red coloured concrete and indirect natural light to create a non-denominational space of quiet contemplation aligned with the cemetery's axial staircase. (Inagawa, Japan)",
    tags: ["sacred", "memorial", "concrete", "water", "garden", "landscape", "light", "shadow", "axis", "threshold", "procession", "stillness", "solemnity"],
    swatches: [
      { hex: "#C4896C", label: "", sourceId: "chipperfield-inagawa-cemetery" },
      { hex: "#8B5A42", label: "", sourceId: "chipperfield-inagawa-cemetery" },
      { hex: "#D4C4B8", label: "", sourceId: "chipperfield-inagawa-cemetery" },
      { hex: "#6E4535", label: "", sourceId: "chipperfield-inagawa-cemetery" },
      { hex: "#B89A8A", label: "", sourceId: "chipperfield-inagawa-cemetery" },
      { hex: "#E8E0D8", label: "", sourceId: "chipperfield-inagawa-cemetery" },
      { hex: "#4A3228", label: "", sourceId: "chipperfield-inagawa-cemetery" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_800/v1620298350/f5xaihqoeizupvcq7dpv/david-chipperfield-architects-edmund-sumner-keiko-sasaoka-inagawa-cemetery-chapel-and-visitor-centre.jpg",
  },
  {
    id: "associates-echo-of-the-mountain",
    name: "Echo of the Mountain",
    architect: "Associates Architecture",
    year: 2024,
    demonstrates: "A circular enclosure of charred timber set on a concrete base isolates a sculpted stone at the centre of a former mine, transforming the site into a monument to the workers' memory within a natural stone amphitheatre. (Dossena, Italy)",
    tags: ["memorial", "public-ground", "concrete", "timber", "stone", "topography", "enclosure", "memory", "identity", "ruin", "austerity", "solemnity"],
    swatches: [
      { hex: "#6B6B5C", label: "", sourceId: "associates-echo-of-the-mountain" },
      { hex: "#A8A898", label: "", sourceId: "associates-echo-of-the-mountain" },
      { hex: "#3A3A30", label: "", sourceId: "associates-echo-of-the-mountain" },
      { hex: "#C8C8B8", label: "", sourceId: "associates-echo-of-the-mountain" },
      { hex: "#8B8B78", label: "", sourceId: "associates-echo-of-the-mountain" },
      { hex: "#D8D4C8", label: "", sourceId: "associates-echo-of-the-mountain" },
      { hex: "#202018", label: "", sourceId: "associates-echo-of-the-mountain" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_800/v1727970947/55868a0a-9737-4459-a572-03cfb045b876/associates-architecture-atelier-xyz-echo-of-the-mountain.jpg",
  },
  {
    id: "banchini-dar-el-farina",
    name: "Dar El Farina",
    architect: "Leopold Banchini Architects",
    year: 2024,
    demonstrates: "A linear rammed-earth house follows two ancient water infrastructures across the Moroccan desert plain, dividing the site into untouched land and a lush garden, with zellige-tiled skylights, water basins and thick mud walls creating a cool microclimate in the desert. (Haouz, Morocco)",
    tags: ["domestic", "rammed-earth", "water", "earth", "light", "shadow", "garden", "microclimate", "vegetation", "vernacular", "threshold", "boundary", "ecology", "stillness"],
    swatches: [
      { hex: "#C8926A", label: "", sourceId: "banchini-dar-el-farina" },
      { hex: "#8B5E3C", label: "", sourceId: "banchini-dar-el-farina" },
      { hex: "#E8D4B8", label: "", sourceId: "banchini-dar-el-farina" },
      { hex: "#4A7A6A", label: "", sourceId: "banchini-dar-el-farina" },
      { hex: "#D4A878", label: "", sourceId: "banchini-dar-el-farina" },
      { hex: "#F0E8D8", label: "", sourceId: "banchini-dar-el-farina" },
      { hex: "#2A5A4A", label: "", sourceId: "banchini-dar-el-farina" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/c_limit,f_auto,h_2000,q_auto,w_3000/v1730816295/f6c3c921-b2c9-410c-8458-b1faa684a59c/leozpold-banchini-architects-rory-gardiner-dar-el-farina.jpg",
  },
  {
    id: "solum-lamia",
    name: "Lamia",
    architect: "SOLUM",
    year: 2025,
    demonstrates: "An existing Apulian stone lamia anchors a three-volume extension whose barrel vaults, tufo and limestone walls, and inhabited connecting spine reinterpret vernacular rural architecture as a flexible contemporary dwelling within an olive-grove landscape. (Ostuni, Italy)",
    tags: ["domestic", "stone", "adaptive-reuse", "landscape", "vegetation", "threshold", "sequence", "vernacular", "dialogue", "permeability", "warmth"],
    swatches: [
      { hex: "#D8D0C0", label: "", sourceId: "solum-lamia" },
      { hex: "#A89880", label: "", sourceId: "solum-lamia" },
      { hex: "#E8E4D8", label: "", sourceId: "solum-lamia" },
      { hex: "#786858", label: "", sourceId: "solum-lamia" },
      { hex: "#C0B8A0", label: "", sourceId: "solum-lamia" },
      { hex: "#F0EDE8", label: "", sourceId: "solum-lamia" },
      { hex: "#504840", label: "", sourceId: "solum-lamia" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1781510946/23e87975-2a5b-4bc1-b070-165b8b74981e/solum-nicolo-panzeri-lamia.jpg",
  },
  {
    id: "coa-tierra-tinta-winery",
    name: "Tierra Tinta Winery",
    architect: "CoA arquitectura",
    year: 2023,
    demonstrates: "Three rammed-earth-walled volumes with diagonal geometries are arranged around an esplanade, orienting views to vines and lake while a serpentine underground cellar dramatises the descent from daylight to the atmosphere of wine maturation. (Aguascalientes, Mexico)",
    tags: ["agricultural", "hospitality", "rammed-earth", "stone", "steel", "landscape", "topography", "earth", "drama", "sequence", "procession", "enclosure"],
    swatches: [
      { hex: "#A88060", label: "", sourceId: "coa-tierra-tinta-winery" },
      { hex: "#C8A080", label: "", sourceId: "coa-tierra-tinta-winery" },
      { hex: "#6B4830", label: "", sourceId: "coa-tierra-tinta-winery" },
      { hex: "#E8D0B0", label: "", sourceId: "coa-tierra-tinta-winery" },
      { hex: "#8B6840", label: "", sourceId: "coa-tierra-tinta-winery" },
      { hex: "#D0B898", label: "", sourceId: "coa-tierra-tinta-winery" },
      { hex: "#3C2818", label: "", sourceId: "coa-tierra-tinta-winery" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/c_limit,f_auto,h_2000,q_auto,w_3000/v1714743677/b96d243c-3075-441d-b716-3c2995c905de/coa-arquitectura-cesar-bejar-tierra-tinta-winery.jpg",
  },
  {
    id: "brh-cascina-elena-winery",
    name: "Cascina Elena Winery",
    architect: "BRH+",
    year: 2021,
    demonstrates: "A biodynamic winery on a Piedmont hillside follows the landscape's contour lines in a horizontal prefabricated steel frame clad in light brown terracotta tiles, minimising excavation and embodying the identity of the Alta Langa terroir through material and colour. (Rocchetta Belbo, Italy)",
    tags: ["agricultural", "hospitality", "steel", "terracotta", "landscape", "topography", "ecology", "vernacular", "identity", "tectonic", "horizon"],
    swatches: [
      { hex: "#A86840", label: "", sourceId: "brh-cascina-elena-winery" },
      { hex: "#C89070", label: "", sourceId: "brh-cascina-elena-winery" },
      { hex: "#6B4020", label: "", sourceId: "brh-cascina-elena-winery" },
      { hex: "#E8C8A0", label: "", sourceId: "brh-cascina-elena-winery" },
      { hex: "#8B5830", label: "", sourceId: "brh-cascina-elena-winery" },
      { hex: "#D0A880", label: "", sourceId: "brh-cascina-elena-winery" },
      { hex: "#3C2010", label: "", sourceId: "brh-cascina-elena-winery" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/f_auto,q_auto,w_600/v1645375143/dec9umhoq2uaq0buzced/brh-aldo-amoretti-cascina-elena-winery.jpg",
  },
  {
    id: "superkilen-urban-revitalization",
    name: "Urban Revitalization Superkilen",
    architect: "Superflex, BIG – Bjarke Ingels Group, TOPOTEK 1",
    year: 2012,
    demonstrates: "A half-mile urban park through Copenhagen's most ethnically diverse neighbourhood is conceived as a global exhibition of found objects contributed by 60 nationalities, fusing landscape, art and architecture to celebrate diversity rather than impose homogeneity. (Copenhagen, Denmark)",
    tags: ["public-ground", "recreational", "civic", "landscape", "identity", "density", "playfulness", "movement", "narrative", "dialogue", "hybrid"],
    swatches: [
      { hex: "#C82020", label: "", sourceId: "superkilen-urban-revitalization" },
      { hex: "#1A1A1A", label: "", sourceId: "superkilen-urban-revitalization" },
      { hex: "#E8D820", label: "", sourceId: "superkilen-urban-revitalization" },
      { hex: "#404040", label: "", sourceId: "superkilen-urban-revitalization" },
      { hex: "#E8E8E8", label: "", sourceId: "superkilen-urban-revitalization" },
      { hex: "#802010", label: "", sourceId: "superkilen-urban-revitalization" },
      { hex: "#606060", label: "", sourceId: "superkilen-urban-revitalization" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/c_limit,f_auto,h_2000,q_auto,w_3000/v1/project_images/3693131/SUK_Image-by-Iwan-Baan_06/superflex-big-bjarke-ingels-group-topotek-1-hanns-joosten-iwan-baan-urban-revitalization-superkilen.jpg",
  },
  {
    id: "supermachine-sac-bangkok",
    name: "SAC: Student Activity Center at Bangkok University",
    architect: "Supermachine Studio",
    year: 2013,
    demonstrates: "A 2,200 sqm student activity centre is threaded through a 20-year-old dormitory structure, transforming a former residential building into a diverse out-of-classroom hub for photo studios, dance clubs and faculty rooms through radical adaptive reuse. (Bangkok, Thailand)",
    tags: ["educational", "institutional", "adaptive-reuse", "hybrid", "playfulness", "movement", "recreational", "density", "circulation"],
    swatches: [
      { hex: "#E8A030", label: "", sourceId: "supermachine-sac-bangkok" },
      { hex: "#40A0D0", label: "", sourceId: "supermachine-sac-bangkok" },
      { hex: "#E04040", label: "", sourceId: "supermachine-sac-bangkok" },
      { hex: "#2A8040", label: "", sourceId: "supermachine-sac-bangkok" },
      { hex: "#D0D0D0", label: "", sourceId: "supermachine-sac-bangkok" },
      { hex: "#808080", label: "", sourceId: "supermachine-sac-bangkok" },
      { hex: "#F0F0F0", label: "", sourceId: "supermachine-sac-bangkok" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/c_limit,f_auto,h_2000,q_auto,w_3000/v1/project_images/4954180/SS-BU-StudentUnion-35/supermachine-studio-wison-tungthunya-w-workspace-sac-student-activity-center-at-bangkok-university.jpg",
  },
  {
    id: "kaan-royal-museum-antwerp",
    name: "Royal Museum of Fine Arts",
    architect: "KAAN Architecten",
    year: 2020,
    demonstrates: "The renovation and hidden extension of Antwerp's 19th-century neoclassical KMSKA museum conceals all new additions within the existing inner structure, restoring the original daylight promenade and reconnecting the building to the city without altering its iconic exterior. (Antwerp, Belgium)",
    tags: ["cultural", "civic", "institutional", "stone", "marble", "adaptive-reuse", "palimpsest", "memory", "procession", "light", "solemnity", "monumentality", "sequence"],
    swatches: [
      { hex: "#E8E0D0", label: "", sourceId: "kaan-royal-museum-antwerp" },
      { hex: "#C8C0B0", label: "", sourceId: "kaan-royal-museum-antwerp" },
      { hex: "#A89888", label: "", sourceId: "kaan-royal-museum-antwerp" },
      { hex: "#F0EDE8", label: "", sourceId: "kaan-royal-museum-antwerp" },
      { hex: "#786858", label: "", sourceId: "kaan-royal-museum-antwerp" },
      { hex: "#D8D0C0", label: "", sourceId: "kaan-royal-museum-antwerp" },
      { hex: "#504840", label: "", sourceId: "kaan-royal-museum-antwerp" },
    ],
    isInfluence: false,
    imageUrl: "https://images.divisare.com//images/c_limit,f_auto,h_2000,q_auto,w_3000/v1614783375/pcrgii0mj5iqs13knhnh/kaan-architecten-stijn-bollaert-sebastian-van-damme-karin-borghouts-royal-museum-of-fine-arts.jpg",
  },
];
